name: Check for n8n Updates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.version-check.outputs.build }}
      new-version: ${{ steps.version-check.outputs.new-version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check n8n latest version
        id: version-check
        run: |
          NEW_VERSION=$(curl -s https://api.github.com/repos/n8n-io/n8n/releases/latest | jq -r .tag_name | sed 's/^n8n@//')
          echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Docker Hub
          REPO_NAME="GG-Beratung/n8n-docker"
          if docker manifest inspect ${REPO_NAME}:${NEW_VERSION} >/dev/null 2>&1; then
            echo "$NEW_VERSION already built"
            echo "build=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Docker Hub n8n image
          echo "Checking if official n8n:$NEW_VERSION image exists on Docker Hub..."
          if docker manifest inspect n8nio/n8n:${NEW_VERSION} >/dev/null 2>&1; then
            echo "Official n8n:$NEW_VERSION image exists on Docker Hub"
            echo "New version $NEW_VERSION found and official image is available"
            echo "build=true" >> $GITHUB_OUTPUT
          else
            echo "Official n8n:$NEW_VERSION image not yet available on Docker Hub"
            echo "Waiting for official image to be published..."
            echo "build=false" >> $GITHUB_OUTPUT
          fi

  trigger-build:
    needs: check-updates
    if: needs.check-updates.outputs.build == 'true'
    uses: ./.github/workflows/build-and-push.yml
    with:
      n8n-version: ${{ needs.check-updates.outputs.new-version }}
    secrets: inherit